In [1]:
import pandas as pd

df = pd.read_csv('../Processed_Headings/normalized_section_data 2.csv')
# df['sec-title'] = df.apply(lambda row: row['xmlPath'].rsplit(' > ', 1)[-1].strip(), axis=1)
# df.to_csv('Processed_Headings/combined.csv')
df.head()

,PMCID,PMID,sec-type,sec-title,sec-norm
0,PMC5427117,28337662,NaN,Introduction,background
1,PMC5427117,28337662,NaN,Methods,methods
2,PMC5427117,28337662,NaN,Results,results
3,PMC5427117,28337662,NaN,Discussion,conclusions
4,PMC5427117,28337662,NaN,Electronic supplementary material,background

In [3]:
import pandas as pd

df_test = pd.read_csv("../data/train_annotated.csv")
df_test

,PMCID,PMID,sec-title,sec-norm
0,PMC11191691,38842535,"['Introduction', 'Results and Discussion', 'Co...","['background', 'conclusions', 'conclusions', '..."
1,PMC11182025,38887617,"['Introduction', 'Materials & Methods', 'Resul...","['background', 'methods', 'results', 'conclusi..."
2,PMC10511328,37704722,"['Main', 'Pooled longitudinal analyses', 'Popu...","['background', 'results', 'results', 'results'..."
3,PMC10632145,37914938,"['Main', 'Population imaging and single-cell a...","['background', 'results', 'results', 'results'..."
4,PMC1084334,15884974,"['Introduction', 'Results', 'Discussion', 'Mat...","['background', 'results', 'conclusions', 'meth..."
...,...,...,...,...
635,PMC11187391,38123960,['Ethics statements'],[nan]
636,PMC11187998,38903349,"['Introduction', 'Case presentation', 'Discuss...","['background', 'methods', 'conclusions', 'conc..."
637,PMC11191920,38905421,"['1. Introduction', '2. Patients and methods',...","['background', 'methods', 'results', 'conclusi..."
638,PMC10978839,38548747,"['Introduction', 'Results', 'Discussion', 'Mat...","['background', 'results', 'conclusions', 'meth..."
639,PMC11187969,38561968,"['Introduction', 'Construction of Chiral Nanom...","['background', 'background', 'background', 'ba..."

In [4]:
import ast
df_test['sec-title'] = df_test['sec-title'].apply(ast.literal_eval)
df_test['sec-title']

0      [Introduction, Results and Discussion, Conclus...
1      [Introduction, Materials & Methods, Results, D...
2      [Main, Pooled longitudinal analyses, Populatio...
3      [Main, Population imaging and single-cell acti...
4      [Introduction, Results, Discussion, Materials ...
                             ...
635                                  [Ethics statements]
636    [Introduction, Case presentation, Discussion, ...
637    [1. Introduction, 2. Patients and methods, 3. ...
638    [Introduction, Results, Discussion, Materials ...
639    [Introduction, Construction of Chiral Nanomate...
Name: sec-title, Length: 640, dtype: object

In [5]:
import numpy as np
def eval_with_nan(x):
    if isinstance(x, list):
        return [np.nan if (isinstance(i, float) and np.isnan(i)) else i for i in x]
    try:
        # 這邊直接 eval 而且給定 locals
        val = eval(x, {"nan": np.nan, "NaN": np.nan, "np": np})
        if isinstance(val, list):
            return [np.nan if (isinstance(i, float) and np.isnan(i)) else i for i in val]
        else:
            return val
    except Exception:
        return x  # 如果 eval 還失敗就原樣保留

In [6]:
df_test['sec-norm'] = df_test['sec-norm'].apply(eval_with_nan)
df_test['sec-norm']

0      [background, conclusions, conclusions, backgro...
1      [background, methods, results, conclusions, co...
2      [background, results, results, results, result...
3      [background, results, results, results, result...
4      [background, results, conclusions, methods, ba...
                             ...
635                                                [nan]
636      [background, methods, conclusions, conclusions]
637    [background, methods, results, conclusions, ba...
638    [background, results, conclusions, methods, ba...
639    [background, background, background, backgroun...
Name: sec-norm, Length: 640, dtype: object

In [7]:
type(df_test['sec-norm'][0])

list

In [8]:
from itertools import chain
texts = list(chain.from_iterable(df_test["sec-title"]))
texts

['Introduction',
 'Results and Discussion',
 'Conclusions',
 'Supplementary Material',
 'Introduction',
 'Materials & Methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Supplemental Information',
 'Additional Information and Declarations',
 'Main',
 'Pooled longitudinal analyses',
 'Population intervention effects',
 'Age-varying effects on growth faltering',
 'Consequences of early growth faltering',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Extended data',
 'Main',
 'Population imaging and single-cell activation',
 'Signal propagation map',
 'Functional measurements differ from anatomy',
 'Extrasynaptic signalling also drives neural dynamics',
 'Extrasynaptic-dependent signal propagation\xa0screen',
 'Signal propagation predicts spontaneous activity',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 'Introduction',
 'Results',
 'Discussion',
 'Materials and Methods',
 'Supporting Information',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Organophosphorus and carbamate pesticide poisioning',
 'Poisoning with other pesticides',
 'Initial assessment of the unconscious patient',
 'Does the patient require atropine? Recognition of OP/carbamate poisoning',
 'Loading with atropine and IV fluids',
 'Observation of the patient',
 'Atropine toxicity',
 'Care of the airway',
 'Active cooling and sedation',
 'Confirmation of exposure to cholinergic compounds',
 'Treatment of the resuscitated and stable patient – should gastric decontamination be performed?',
 'Oximes and other therapies',
 'Care after the first few hours',
 'Conclusions',
 'Key messages',
 'Competing interests',
 'Abbreviations',
 'Supplementary Material',
 'Figures and Tables',
 'Main',
 'Results',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Extended data',
 'To the Editor,',
 'Case Presentation',
 'Discussion and Conclusions',
 'Electronic Supplementary Material',
 'Main',
 'Results',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 'Background',
 'Methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Background',
 'Results',
 'Discussion',
 'Conclusion',
 'Methods',
 'Competing interests',
 "Authors' contributions",
 'Introduction',
 'Results',
 'Discussion',
 'Conclusions',
 'Methods and materials',
 'Supplementary Information',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Supplementary Information',
 'Introduction',
 'Results',
 'Discussion',
 'Conclusion',
 'Material and methods',
 'Supplementary Information',
 'Introduction',
 'Materials and methods',
 'Results & discussion',
 'Conclusion',
 'Supporting information',
 'Introduction',
 'Materials and methods',
 'Results and discussion',
 'Conclusions',
 'Supporting information',
 'Introduction',
 'Results and Discussion',
 'Conclusion',
 'Supporting Information',
 'Data Availability',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 'Supplementary material',
 'Funding',
 'Disclosure',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Supplementary information',
 'Background',
 'Methods',
 'Results',
 'Discussion',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Data availability statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 '1 Introduction',
 '2 Materials and methods',
 '3 Results',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Supplementary material',
 'Experimental Implementation.',
 'Experimental Results.',
 'Discussion',
 'Conclusion',
 'Supplementary Material',
 'Data, Materials, and Software Availability',
 'Supporting Information',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Electronic supplementary material',
 '1. Introduction',
 '2. Models for Correlation of Local Lesion Host and Virus Concentration',
 '3. Evaluating Goodness of Fit for Various Models Applied to Experimental Data',
 '4. Machine Learning and Artificial Intelligence in Quantification of Viruses Using Local Lesions',
 '5. Application of Infectivity Dilution Curve in Virucidal Efficacy of Disinfectants',
 '6. Conclusions',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusion and future directions',
 'Supplementary Material',
 'Data availability',
 'Funding',
 'Conflict of interest',
 'Introduction',
 'Materials and methods',
 'Results',
 'Code availability',
 'Supplementary Material',
 'Supplementary material',
 'Competing interests',
 'Author contributions statement',
 'Introduction',
 'Case Report',
 'Discussion',
 'Introduction',
 'Results and Discussion',
 'Conclusion',
 'Supporting Information',
 'Data Availability',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Supplementary Material',
 'Author contributions',
 'Conflict of interest',
 'Funding',
 'Data availability',
 'Introduction',
 'Case presentation',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Results',
 'Discussion',
 'Methods',
 'Supplementary Information',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Limitations',
 'Conclusions',
 'Introduction',
 'Materials and Methods',
 'Results',
 'Discussion',
 'Supplementary Material',
 'Introduction',
 'Arrhythmia substrates in congenital heart disease',
 'Management of arrhythmias in congenital heart disease',
 'Specific arrhythmia types',
 'Author contributions',
 'Conflict of interest',
 "Publisher's note",
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Supporting information',
 '1. Introduction',
 '2. Methods',
 '3. Validation',
 '4. Results and discussion',
 '5. Conclusion',
 'Supporting information',
 '1 Introduction',
 '2 Methods',
 '3 Results',
 '4 Discussion',
 '5 Conclusion',
 'Data availability statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'INTRODUCTION',
 'METHODS',
 'RESULTS',
 'DISCUSSION',
 'SUPPLEMENTARY MATERIAL',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Introduction',
 'Results and discussion',
 'Concluding remarks',
 'Methods',
 'Introduction',
 'Methods',
 'Results',
 'Discussion and policy recommendations',
 'Data availability statement',
 'Ethics statements',
 'Introduction',
 'Structure, functions, and biochemical composition of leaves',
 'Beneficial health effects of popular and exotic fruit plant leaves',
 'Possible applications of leaves in the food industry',
 'Conclusion',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 'Main',
 'A scalable generative model for protein systems',
 'Analysis of unconditional samples',
 'Programmability',
 'Experimental validation',
 'Discussion',
 'Online content',
 'Supplementary information',
 'Extended data',
 'Introduction',
 'Materials and methods',
 'Results and discussion',
 'Conclusion',
 'Conflict of interest',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Methods',
 'Supplementary Material',
 'Introduction',
 'Material and methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Supporting information',
 '1. Introduction',
 '2. Materials and methods',
 '3. Results',
 '4. Discussion',
 '5. Conclusion',
 '6. Study limitation',
 'Main',
 'Results',
 'Discussion',
 'Conclusion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 'Main',
 'Results',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Extended data',
 'Introduction',
 'Mosul Dam, its foundation, and a brief history of sinkholes development',
 'Testing materials and methods',
 'Results and discussion',
 'Conclusions',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion and conclusions',
 'Ethical approval',
 'Author’s contribution',
 'Disclosure statement',
 'Data availability statement',
 'Introduction',
 'Feminist debates on categories: gender, sexuality and intersectionality',
 'How to capture these categories in surveys',
 'The consequences of limiting sociodemographic variables: the case of the European values study',
 'Proposal of sociodemographic questions that include the categories of sex, gender and sexual orientation',
 'Discussion and conclusion',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Concluding Remarks',
 'Main',
 'Cas1–Cas2/DEDDh substrate generation',
 'PAM binding and prespacer processing',
 'PAM trimming after half-integration',
 'CRISPR array integration reconstitution',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 'Introduction',
 'Case presentation',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Materials and methods',
 'Tolerance to pH and bile salt',
 'Hemolysis test',
 'Result',
 'Discussion',
 'Electronic supplementary material',
 'Introduction',
 'Results',
 'Discussion',
 'Conclusion',
 'Materials and Methods',
 'Supplementary Material',
 'TO THE EDITOR:',
 'Introduction',
 'Results',
 'Discussion',
 'Conclusion',
 'Experimental Section',
 'Conflict of interest',
 'Author Contributions',
 'Supporting information',
 'Data Availability Statement',
 'INTRODUCTION',
 'MATERIALS AND METHODS',
 'RESULTS',
 'DISCUSSION',
 'FUNDING',
 'CONFLICT OF INTEREST',
 'DATA AVAILABILITY',
 'ETHICAL APPROVAL',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 'Supplementary material',
 'Introduction',
 'Results',
 'Discussion',
 'Methods',
 'Supplementary Information',
 'Introduction',
 'Review of the literature',
 'Data and methodology',
 'Results and discussion',
 'Conclusions and policy recommendations',
 'Disclaimer',
 'Data statement',
 'Supplementary material',
 'Introduction',
 'Experiment 1',
 'Experiment 2',
 'General discussion',
 'Funding Information',
 'Additional information',
 'Additional files',
 'Data availability',
 'Introduction',
 'Materials and Methods',
 'Results and Discussion',
 'Conclusions',
 'Supplementary Material',
 'Results',
 'Discussion',
 'Methods',
 'Supplementary Information',
 'Main',
 'Methods',
 'Supplementary information',
 'Source data',
 'Extended data',
 'Conclusion',
 'Competing interests',
 '1 Introduction',
 '2 Methods and materials',
 '3 Result',
 '4 Discussion',
 '5 Conclusion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Supplementary material',
 'Background',
 'Methods',
 'Results',
 'Discussion',
 'Conclusion',
 "Authors' contributions",
 'History and Epidemiology',
 'Causative Organism and Pathology',
 'Clinical Features',
 'Treatment',
 'Prevention of Disabilities',
 'Public Health Efforts',
 'Why Has Buruli Ulcer Been Neglected until Now?',
 'Future Directions and the End of Obscurity',
 'Conclusion',
 'Introduction to the behavioural task',
 'Objectives',
 'Overview of the procedure',
 'Hazards',
 'Control measures',
 'Materials',
 'Procedure',
 'Data',
 'Additional steps',
 'Troubleshooting',
 'Supplementary Material',
 'Supplementary material',
 'Funding',
 'Competing interests',
 'Data availability',
 'Introduction',
 'Case presentation',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Results',
 'Discussion',
 'Materials and methods',
 'Funding Information',
 'Additional information',
 'Additional files',
 'Data availability',
 'Introduction',
 'BL-IGHV CLL cohort',
 'Results and discussion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Introduction',
 'Methods and analysis',
 'Discussion',
 'Ethics and dissemination',
 'Conclusion',
 'Supporting Information',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Supplementary Material',
 'Data availability',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Background & Summary',
 'Methods',
 'Data Records',
 'Technical Validation',
 'Usage Notes',
 'Supplementary information',
 'Introduction',
 'Results and Discussion',
 'Conclusions',
 'Methods',
 'Supplementary Material',
 'Introduction',
 'Results',
 'Discussion',
 'Experimental procedures',
 'Supplementary Information',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Supplementary information',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Introduction',
 'Subjects and Methods',
 'Results',
 'Discussion',
 'Supplementary information',
 'Introduction',
 'Results',
 'Discussion',
 'Conclusion',
 'Electronic supplementary material',
 'Introduction',
 'Results',
 'Discussion',
 'Methods',
 'Supplementary information',
 'INTRODUCTION',
 'MATERIALS AND METHODS',
 'RESULTS',
 'DISCUSSION',
 'CONCLUSION',
 'AUTHOR CONTRIBUTIONS',
 'FUNDING INFORMATION',
 'CONFLICT OF INTEREST STATEMENT',
 'ETHICS STATEMENT',
 'PATIENT CONSENT STATEMENT',
 'PERMISSION TO REPRODUCE MATERIAL FROM OTHER SOURCES',
 'DATA AVAILABILITY STATEMENT',
 'Background',
 'Case presentation',
 'Discussion',
 'Conclusions',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Key messages',
 'Competing interests',
 'Abbreviations',
 'Figures and Tables',
 'Health Benefits of Physical Activity',
 'Translating Knowledge of Exercise Biology to Novel Therapeutics',
 'Physiological Properties of Skeletal Muscle',
 'Dynamics of Muscle Mass',
 'Contractile and Metabolic Properties',
 'Molecular Signaling Pathways',
 'Cellular Memory',
 'Summary and Conclusions',
 'Introduction',
 'Results and discussion',
 'Methods',
 'Supplementary information',
 'Introduction and background',
 'Review',
 'Conclusions',
 'Introduction',
 'Materials and methods',
 'Results and discussion',
 'Conclusions',
 'Supporting information',
 'CONFLICT OF INTEREST STATEMENT',
 'Supporting information',
 'DATA AVAILABILITY STATEMENT',
 'Introduction',
 'Results',
 'Discussion',
 'Material and methods',
 'Supplementary Information',
 'Introduction',
 'Results',
 'Discussion',
 'Materials and Methods',
 'Supporting Information',
 'Introduction',
 'Results',
 'Discussion',
 'Materials and methods',
 'Supporting information',
 'Introduction',
 'Results',
 'Discussion',
 'Materials and methods',
 'Funding Information',
 'Additional information',
 'Additional files',
 'Data availability',
 'Introduction',
 'Methods',
 'Results and Discussion',
 'Conclusions',
 'Supplementary Material',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'INTRODUCTION',
 'METHODS',
 'RESULTS',
 'DISCUSSION',
 'Supplementary Material',
 'DATA AVAILABILITY STATEMENT',
 '1 Introduction',
 '2 Materials and methods',
 '3 Results',
 '4 Discussion',
 '5 Conclusion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher‚Äôs note',
 'Supplementary material',
 'INTRODUCTION',
 'DEVELOPMENT OF LLMs IN HEALTH CARE',
 'APPLICATIONS OF LLMs IN HEALTH CARE',
 'CHALLENGES OF LLMs IN HEALTH CARE',
 'CONCLUSION',
 'AUTHOR CONTRIBUTIONS',
 'CONFLICT OF INTEREST STATEMENT',
 'ETHICS STATEMENT',
 'INFORMED CONSENT',
 'DATA AVAILABILITY STATEMENT',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'supplementary material',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Supplementary Information',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusion',
 'Data availability statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 'Supplementary material',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Conclusions',
 'INTRODUCTION',
 'RESULTS',
 'DISCUSSION',
 'MATERIALS AND METHODS',
 'Supplementary Material',
 'Peer review history',
 'Main',
 'UREL UFMylates 60S ribosomes',
 'Overall structure of the 60S–UREL–UFC1–UFM1 complex',
 'The architecture of UREL',
 'Mode of ribosome recognition by UREL',
 'PTC remodelling by UFL1',
 'UREL binds to UFMylated 60S through the UFIM motif',
 'Catalytic mechanism',
 'UFMylation dissociates SEC61 from 60S',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 'INTRODUCTION',
 'MATERIAL AND METHODS',
 'RESULTS',
 'DISCUSSION',
 'CONCLUSION',
 'CONFLICT OF INTEREST',
 'Supporting information',
 'Main',
 'A long paired temperature–hydroclimate record',
 'From energy- to moisture-limited climate',
 'Future climate in the Horn of Africa',
 'Methods',
 'Online content',
 'Supplementary information',
 'Extended data',
 'Main',
 'Formulations and algorithms',
 'In silico results and analysis',
 'Results for COVID-19 mRNA vaccines',
 'Results for VZV mRNA vaccines',
 'Discussion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 'Main',
 'Methods',
 'Supplementary information',
 'Extended data',
 'Introduction',
 'Methods',
 'Results',
 'Discussion',
 'Supplementary Material',
 'Funding',
 'Author contributions',
 'Disclosure',
 'Supplementary material',
 'Data availability',
 'Introduction',
 'Results',
 'Discussion',
 'Materials and methods',
 'Supplementary information',
 '1 EGFR突变可切除的NSCLC术后辅助治疗研究进展',
 '2 EGFR突变可切除的NSCLC新辅助治疗研究进展',
 '3 围手术期辅助EGFR-TKIs靶向治疗方案问题探讨',
 'Main',
 'Synthetic theorems and proofs generation',
 'Generating proofs beyond symbolic deduction',
 'Training a language model on synthetic data',
 'Combining language modelling and symbolic engines',
 'Empirical evaluation',
 'Geometry theorem prover baselines',
 'Proving results on IMO-AG-30',
 'Conclusion',
 'Methods',
 'Online content',
 'Supplementary information',
 'Source data',
 'Extended data',
 '1 Introduction',
 '2 Related work',
 '3 System model',
 '4 Hybrid optimization algorithm',
 '5 High entropy energy saving clustering routing algorithm',
 '6 Simulation results',
 '7 Conclusion and future work',
 'Background',
 'Methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Electronic supplementary material',
 'INTRODUCTION',
 'METHODS',
 'RESULTS',
 'DISCUSSION',
 'SUPPLEMENTARY MATERIAL',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Conclusions',
 'Supplementary Information',
 'Introduction and background',
 'Review',
 'Conclusions',
 'Introduction',
 'Materials and methods',
 'Results',
 'Discussion',
 'Data availability statement',
 'Ethics statement',
 'Author contributions',
 'Conflict of interest',
 'Publisher’s note',
 'Supplementary material',
 'A World of Contrasts',
 'Open Access to the Medical Literature: Critical for Our Future',
 'The Influence of the Pharmaceutical Industry',
 'The Need for Student Ideals and Ideas',

In [9]:

from sentence_transformers import SentenceTransformer, InputExample, losses
fine_tuned_model = SentenceTransformer("all-MiniLM-L6-v2")

# 測試新模型
embeddings = fine_tuned_model.encode([text.lower() for text in texts])

In [10]:
print(fine_tuned_model.tokenizer.model_max_length)

256

In [12]:
token_lens = []

for sent in texts:
    tokens = fine_tuned_model.tokenizer(
        sent,
        truncation=False,           # 不要截斷，讓我們看到原始長度
        return_attention_mask=False,
        return_token_type_ids=False
    )
    token_lens.append(len(tokens["input_ids"]))

import numpy as np
print(f"🔍 Token length stats:")
print(f"  Max: {max(token_lens)}")
print(f"  Mean: {np.mean(token_lens):.2f}")
print(f"  95th percentile: {np.percentile(token_lens, 95):.2f}")

🔍 Token length stats:
  Max: 44
  Mean: 4.53
  95th percentile: 9.00

In [13]:
import numpy as np

np.save("comparison/embeddings_test_lower0.npy", embeddings)

In [14]:
norms = list(chain.from_iterable(df_test["sec-norm"]))
norms

['background',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'results',
 'results',
 'results',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'results',
 'results',
 'results',
 'results',
 'results',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'objective',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 nan,
 nan,
 nan,
 nan,
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'background',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 nan,
 nan,
 nan,
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'results',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 nan,
 nan,
 nan,
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'results',
 'results',
 'results',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 nan,
 nan,
 nan,
 nan,
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'conclusions',
 'background',
 'results',
 'results',
 'results',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'methods',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 nan,
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'methods',
 'conclusions',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'results',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'results',
 'methods',
 'background',
 'background',
 'background',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'conclusions',
 'conclusions',
 'background',
 'objective',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'background',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'results',
 'conclusions',
 'background',
 'background',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'conclusions',
 'background',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'conclusions',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 nan,
 nan,
 nan,
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'results',
 'results',
 'results',
 'results',
 'results',
 'results',
 'results',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'results',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'results',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'results',
 'methods',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 nan,
 nan,
 nan,
 'background',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'methods',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'methods',
 'methods',
 'results',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'methods',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 nan,
 nan,
 nan,
 nan,
 'conclusions',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'conclusions',
 nan,
 nan,
 nan,
 nan,
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'results',
 'conclusions',
 'methods',
 'background',
 'background',
 'methods',
 'conclusions',
 'background',
 'methods',
 'conclusions',
 'conclusions',
 'background',
 'results',
 'conclusions',
 'conclusions',
 'methods',
 'background',
 'background',
 'background',
 'background',
 'methods',
 'results',
 'conclusions',
 'conclusions',
 'background',
 'methods',
 'results',
 'conclusions',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 'background',
 ...]

In [15]:
label2id = {
     "methods" : 0,
     "background" : 1,
     "results" : 2,
     "conclusions" : 3, 
     "objective": 4
}
labels = np.array([label2id[label] if label in label2id else -1 for label in norms])
np.save("comparison/labels_lower0.npy", labels)